---
params: 
  time_point: t1
title: "AHHA (At-Home Health Assessment) Review"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document:  
    latex_engine: xelatex
    toc: true
    toc_depth: 5
    number_sections: true
    highlight: tango
    fig_width: 12
    fig_height: 12
header-includes:
   \usepackage{float}
    \floatplacement{figure}{H}
    \usepackage{longtable}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      message= F, 
                      warning = F, 
                      comment=NA, 
                      results = "hide", 
                      tidy.opts=list(width.cutoff=60), 
                      tidy=TRUE)

```

# Review for time-point `r params$time_point`

```{r}
source(here::here("main.R"))
```

```{r}
# [AHHA] Review Data
ahha <- vroom(
  paste0(cle_p, "ahha_ss.csv"),
  col_types = c(.default = "c")
  ) 

# Birth days from registration
bd <- vroom(
  paste0(cle_p, "ss_id_bday.csv"),
  col_types = c(.default = "c")
) %>% clean_names

# Sex from survey
sx <- vroom(
  paste0(cle_p, "ss_id_sex.csv"),
  col_types = c(.default = "c")
) 

df <- ahha %>% 
  left_join(bd, by = "id") %>%
  left_join(sx, by = "id")

df <- df %>% 
  mutate(
    myob = my( #month and year of birth
      paste0(birthday_month, birthday_year)
      ),
    dob = myob - 1 + 1/2 * days_in_month(
      month(
        myob
        )
      ),
    age = time_to_from(as_date(date), dob, "years"),
    age_days = time_to_from(as_date(date), dob, "days"),
    across(
      c(bm_kg, ht_cm), 
      ~ as.numeric(.x)
      ),
    across(
      matches("(role|choice|hair|pregnant|bf)$"),
      ~ as.factor(.x)
    ),
    child_sex = case_when(
      sex_selected_choice == "Male" ~ 1,
      sex_selected_choice == "Female" ~ 2,
      TRUE ~ NA_real_
    ),
    gender = coalesce(sex_selected_choice, gender_selected_choice)
  ) %>% 
  add_column(
    convert_ht_inches_to_cm = NA,
    convert_bm_lbs_to_kg = NA
  ) %>% 
  arrange(
    fid,
    id
  ) %>% 
  addWGSR(
    data = .,
    sex = "child_sex",
    firstPart = "bm_kg",
    secondPart = "ht_cm",
    thirdPart = "age_days",
    index = "bfa"
  ) %>%
  rename(bmi_z = bfaz)

```


```{r}
# For box plot fence calculation, use 1 parent and 1 child from each family

sample_one_role <- df %>% 
  group_by(
    role
  ) %>% 
  distinct(
    fid,
    .keep_all = T
  ) 

cuts_labs <- list(
  cutpoints = ~ cuts(.x), 
  cutlabels = ~ names(cuts(.x))
)

cinames <- c("ht_cm", "bm_kg", "bmi_z")

wide <- sample_one_role %>% 
  group_by(role) %>%
  summarize(
    across(
      all_of(cinames),
      cuts_labs,
      .names = "{.fn}_{.col}"
      )
  ) 

```


```{r}
long <- wide %>% 
  mutate(
    cut_point = cutlabels_bm_kg
  ) %>% 
  select(
    everything(),
    -contains("cutlabels")
    ) %>% 
  pivot_longer(
    !c(role, cut_point), 
    names_to = "measure", 
    names_prefix = "cutpoints_",
    values_to = "measure_value",
  ) 

quantiles <- long %>% 
  pivot_wider(
    names_from = cut_point,
    values_from = measure_value
  )

long_df <- df %>% 
  pivot_longer(
    all_of(cinames),
    names_to = "measure",
    values_to = "measure_value"
  ) 
```

```{r}
measures <- long_df %>% 
  full_join(
    quantiles,
    by = c("role", "measure")
  ) %>% 
  mutate(
    i_extreme = case_when(
      measure_value < LW | measure_value > HW ~ 1,
      LW < measure_value | measure_value < HW ~ 0,
      TRUE ~ as.numeric(NA)
    ),
    across(
      where(is.numeric),
      ~ round(.x, 2)
    )
  )

extremes <- measures %>% 
  select( 
    role,
    id, 
    age, 
    gender,
    i_extreme, measure, measure_value, LW, HW
  ) %>%
  rename(
    value = measure_value
  ) %>%
  filter(
    i_extreme == "1"
  ) %>% 
  arrange(
    measure,
    role
  )

```

## Sample Overview

Whiskers LW and HW are cut-off values from Adjusted Box-Plots. 0% to 100% are percentiles where 0% is the minimum and 100% the maximum value.

```{r results = "as is"}
quantiles_formatted <- quantiles %>% 
    relocate(c(LW, HW), .before = "0%") %>% 
    mutate(
      across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )

datatable(
  quantiles_formatted,
  options = list(
    dom = 't'
    ),
  rownames = F
)
```

## Extremes in Data

```{r results = "as is"}
dt(extremes)
```


# Data 
```{r}
df <- df %>% 
  mutate(
    across(
      where(is.numeric),
      ~ round(.x, 2)
    )
  )

pdf <- df %>%
  filter(
    role == "parent"
  ) %>% 
  select(
    id,
    age,
    gender,
    pregnant,
    bf,
    comments,
    ht_cm,
    bm_kg,
    bm_choice
  ) 

cdf <- df %>%
  filter(
    role == "child"
  ) %>%
  select(
    id,
    age,
    gender,
    wc_cm,
    wc_notes,
    ht_cm,
    bm_kg,
    bmi_z,
    ht_bm_notes,
    comments,
    bm_choice,
    ht_choice
    )
```


### Parents

Note: Parent 2's ages have yet to be coded.

```{r results = "as is"}
dt(pdf)

```

### Children

```{r results = "as is"}
dt(cdf)
```




